CREATE DATABASE yeticave;
USE yeticave;

CREATE TABLE category (
  id TINYINT(3) AUTO_INCREMENT PRIMARY KEY,
  name CHAR(30) NOT NULL,
  UNIQUE (name)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE lot (
  id SERIAL,
  add_user_id BIGINT(20) UNSIGNED NOT NULL,
  win_user_id BIGINT(20) UNSIGNED NOT NULL,
  category_id INT(3) UNSIGNED NOT NULL,
  name CHAR(50) NOT NULL,
  description TEXT NOT NULL,
  img CHAR(30) NOT NULL,
  price FLOAT(10) UNSIGNED NOT NULL,
  price_step INT(10) UNSIGNED NOT NULL,
  time_add INT(11) UNSIGNED NOT NULL,
  time_end INT(11) UNSIGNED NOT NULL,
  INDEX (add_user_id, category_id, name)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE rate (
  id SERIAL,
  user_id BIGINT(20) UNSIGNED NOT NULL,
  lot_id BIGINT(20) UNSIGNED NOT NULL,
  time INT(11) UNSIGNED NOT NULL,
  price INT(10) UNSIGNED NOT NULL,
  INDEX (user_id, lot_id)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE user (
  id SERIAL,
  email CHAR(50) NOT NULL,
  name CHAR(30) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  avatar CHAR(30),
  contact CHAR(50) NOT NULL,
  UNIQUE (email)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;
